apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuerName }}
  labels:
    {{- include "letsencrypt-issuer.labels" . | nindent 4 }}
spec:
  acme:
    server: '{{ .Values.acme.server }}'
    email: '{{ .Values.acme.email }}'
    privateKeySecretRef:
      name: {{ include "letsencrypt-issuer.fullname" . }}-acme
    solvers:
      - dns01:
          cloudflare:
            email: '{{ .Values.cloudflare.email }}'
            apiTokenSecretRef:
              name: {{ include "letsencrypt-issuer.fullname" . }}
              key: cloudflare-token
        {{- with .Values.acme.zones }}
        selector:
          dnsZones:
            {{- range . }}
            - '{{ . }}'
            {{- end }}
        {{- end }}
