apiVersion: v1
kind: Secret
metadata:
  name: {{ include "letsencrypt-issuer.fullname" . }}
  labels:
    {{- include "letsencrypt-issuer.labels" . | nindent 4 }}
type: Opaque
data:
  cloudflare-token: {{ b64enc .Values.cloudflare.token }}
