{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gitlab-omnibus.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gitlab-omnibus.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- with .Values.ingress.hosts.gitlab }}
    - host: {{ .url | quote }}
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{- end }}
    {{- with .Values.ingress.hosts.pages }}
    - host: {{ .url | quote }}
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{- end }}
    {{- with .Values.ingress.hosts.registry }}
    - host: {{ .url | quote }}
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{- end }}
  {{- end }}
