{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "gitlab-omnibus.fullname" . }}
  labels:
    {{- include "gitlab-omnibus.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.podMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gitlab-omnibus.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: wh-metrics
    - port: gitaly-metrics
    - port: http
      path: /-/metrics
{{- end }}
