{{- $fullname := include "adguard.fullname" . }}
{{- $labels := include "adguard.labels" . }}
{{- $user := .Values.adguard.config.users | first }}
{{- with .Values.prometheusExporter }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-exporter
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
data:
  user: {{ b64enc $user.name }}
  password: {{ b64enc $user.password }}
{{- end }}
{{- end }}
