apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}-http
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}-dns-tcp
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}-dns-udp
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }}
