apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tfstate-postgres.fullname" . }}-user
  labels:
    {{- include "tfstate-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ b64enc .Values.user.user }}
  password: {{ b64enc .Values.user.password }}
