{{- if .Values.backup.enabled }}
{{- $fullname := include "gotify.fullname" .}}
apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ $fullname }}-backup-init'
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: restic-init
          image: restic/restic:0.14.0
          command:
            - sh
            - -c
            - restic snapshots || restic init
          env:
            - name: RESTIC_REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: '{{ $fullname }}-backup'
                  key: resticRepository
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ $fullname }}-backup'
                  key: resticRepositoryPassword
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: '{{ $fullname }}-backup'
                  key: s3AccessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: '{{ $fullname }}-backup'
                  key: s3SecretKey
      restartPolicy: OnFailure
{{- end }}
