{{- $fullname := include "backup.fullname" . }}
{{- $labels := include "backup.labels" . }}
{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-repo-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
data:
  address: {{ b64enc .address }}
  password: {{ b64enc .password }}
---
{{- end }}
